/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reservationhotel.gui;

import java.awt.Dimension;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import reservationhotel.agents.ClientAgent;
import reservationhotel.ontology.BesoinsClient;

/**
 *
 * @author Basile
 */
public class ClientGui extends javax.swing.JFrame {

    ClientAgent clientAgent;

    /**
     * Creates new form ClientGuiReponse
     */
    public ClientGui(ClientAgent clientAgent) {
        this.clientAgent = clientAgent;
        initComponents();
        setSize(370, 350);
        //setFocusable(true);
    }

    boolean EstVide() {
        boolean rep = true;
        if (txtFieldLocalite.toString().isEmpty()
                || datDebut.getValue()==null
                || datFin.getValue()==null
                || (int) spinPrixMax.getValue() <= 0 
                || (int) spinPrixMin.getValue() <= 0) {
            rep = true;
        }else{
            rep = false;
        }
        return rep;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFieldLocalite = new javax.swing.JTextField();
        btnRechercher = new javax.swing.JButton();
        btnAnnuler = new javax.swing.JButton();
        cbTypChambre = new javax.swing.JComboBox();
        spinPrixMin = new javax.swing.JSpinner();
        spinPrixMax = new javax.swing.JSpinner();
        datDebut = new javax.swing.JFormattedTextField();
        datFin = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtFieldLocalite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldLocaliteActionPerformed(evt);
            }
        });

        btnRechercher.setText("Rechercher");
        btnRechercher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRechercherMouseClicked(evt);
            }
        });
        btnRechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechercherActionPerformed(evt);
            }
        });

        btnAnnuler.setText("Annuler");
        btnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerActionPerformed(evt);
            }
        });

        cbTypChambre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SIMPLE", "VIP" }));

        datDebut.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        datFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        datFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datFinActionPerformed(evt);
            }
        });

        jLabel1.setText("Critères de recherche");

        jLabel2.setText("Localité");

        jLabel4.setText("Type chambre");

        jLabel5.setText("Date début");

        jLabel6.setText("Date fin");

        jLabel7.setText("Prix min");

        jLabel8.setText("Prix max");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnRechercher)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAnnuler)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(spinPrixMin, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(spinPrixMax, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(datFin, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(datDebut, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbTypChambre, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFieldLocalite, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(59, 59, 59))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldLocalite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbTypChambre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinPrixMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinPrixMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRechercher)
                    .addComponent(btnAnnuler))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datFinActionPerformed

    private void txtFieldLocaliteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldLocaliteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldLocaliteActionPerformed

    private void btnRechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechercherActionPerformed
        // TODO add your handling code here: 
        if (EstVide()) {
            infoBox("Veuillez remplir tous les champs");
        }else{
                    btnRechercher.setEnabled(false);
        BesoinsClient besoinClient = new BesoinsClient();
        //besoinClient.setNom(txtFieldNomClient.getText());
        besoinClient.setLocalite(txtFieldLocalite.getText());
        besoinClient.setTypeChambre("VIP");
        //besoinClient.setPrixMax((int) spinPrixMax.getValue());
        String pattern = "dd/MM/yyyy";
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
        String date1 = simpleDateFormat.format(datDebut.getValue());
        datDebut.setText(date1);
        String date2 = simpleDateFormat.format(datFin.getValue());
        datFin.setText(date2);
        //System.out.println("Date1 = "+date1);
        //System.out.println("Date2 = "+date2);
        besoinClient.setDatArrive((Date) datDebut.getValue());
        besoinClient.setDatDepart((Date) datFin.getValue());
        besoinClient.setPrixMax((int) spinPrixMax.getValue());
        besoinClient.setPrixMin((int) spinPrixMin.getValue());
        afficheBesoinClient(besoinClient);
        clientAgent.setUserRequest(besoinClient);
        }

    }//GEN-LAST:event_btnRechercherActionPerformed

    private void btnRechercherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRechercherMouseClicked
        // TODO add your handling code here:      
    }//GEN-LAST:event_btnRechercherMouseClicked

    private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnAnnulerActionPerformed

    public void infoBox(String infoMessage) {
        JOptionPane.showMessageDialog(this, infoMessage, "Aucune offre ", JOptionPane.INFORMATION_MESSAGE);
    }

    void afficheBesoinClient(BesoinsClient bs) {
        System.out.println("Agent client : Affichage du besoin client");
        System.out.println("Localité = " + bs.getLocalite());
        System.out.println("Type chambre = " + bs.getTypeChambre());
        System.out.println("Date arrive = " + bs.getDatArrive());
        System.out.println("Date depart = " + bs.getDatDepart());
        System.out.println("Prix min = " + bs.getPrixMin());
        System.out.println("Prix Max = " + bs.getPrixMax());
    }

    public void clearZoneEdit() {
        btnRechercher.setEnabled(true);
        txtFieldLocalite.setText("");
        datDebut.setText("");
        datFin.setText("");
        spinPrixMax.setValue(0);
        spinPrixMin.setValue(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnRechercher;
    private javax.swing.JComboBox cbTypChambre;
    private javax.swing.JFormattedTextField datDebut;
    private javax.swing.JFormattedTextField datFin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSpinner spinPrixMax;
    private javax.swing.JSpinner spinPrixMin;
    private javax.swing.JTextField txtFieldLocalite;
    // End of variables declaration//GEN-END:variables
}
